#!/bin/bash
# =============================================================================
#  Installer for the MANAGEMENT HOST (the one that will run the web panel).
#
#  Installs/updates EVERYTHING this host needs, in one go:
#    1) Ollama (official installer from ollama.com)
#    2) LiteLLM (gateway aggregator, via `uv tool install`, no root)
#    3) Open WebUI (chat panel, `uv tool install --python 3.11`, no root) -
#       installs the binary only, does NOT start/enable the service - that's
#       left to the Start/autostart button in the panel's WebUI tab on purpose
#       (heavy service, not everyone wants it running right away)
#    4) nfs-kernel-server - export server for remote hosts (BC-250 etc.),
#       per-host exports themselves are managed by the daemon (Slave tab)
#    5) octollama-daemon (root, system systemd unit) - controls the local
#       Ollama service EXCLUSIVELY through state.json (see README.md, Architecture)
#    6) octollama-web (no root, systemd --user) - the login web panel
#
#  For a REMOTE host (e.g. BC-250) that only needs Ollama + the daemon, not the
#  web panel or LiteLLM - use the script generated by the web panel itself
#  (README.md, "Multi-host" section), not this file.
#
#  Detects an existing OctoLlama install and offers to update it, or to
#  reinstall the same version. A newer version already installed than the one
#  in this checkout warns before overwriting.
#
#  Run:       ./install.sh
#  Uninstall: ./install.sh --uninstall
# =============================================================================
set -euo pipefail

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"
DAEMON_SRC="$SCRIPT_DIR/daemon"
WEB_SRC="$SCRIPT_DIR/web"
NEW_VERSION="$(cat "$SCRIPT_DIR/VERSION" 2>/dev/null || echo "0.0.0")"

DAEMON_DIR="/opt/octollama/daemon"
STATE_DIR="/var/lib/octollama/state"
DAEMON_UNIT_DST="/etc/systemd/system/octollama-daemon.service"
HOSTS_BASE="/srv/octollama/hosts"
EXPORTS_FILE="/etc/exports.d/octollama.exports"

WEB_DIR="$HOME/.local/share/octollama-web"
WEB_UNIT_DST="$HOME/.config/systemd/user/octollama-web.service"

INSTALLED_VERSION_FILE="$WEB_DIR/VERSION"
PORT_FILE="$WEB_DIR/PORT"

_compare_versions() {
    # "older"/"same"/"newer" for version $1 relative to $2.
    if [ "$1" = "$2" ]; then
        echo "same"
    elif [ "$(printf '%s\n%s\n' "$1" "$2" | sort -V | head -n1)" = "$1" ]; then
        echo "older"
    else
        echo "newer"
    fi
}

# =============================================================================
#  Uninstall
# =============================================================================
remove_app() {
    if [ ! -d "$WEB_DIR" ] && [ ! -d "$DAEMON_DIR" ]; then
        echo "OctoLlama is not installed - nothing to remove." >&2
        exit 1
    fi

    echo "Removing OctoLlama..."

    if systemctl --user list-unit-files octollama-web.service >/dev/null 2>&1; then
        systemctl --user disable --now octollama-web.service 2>/dev/null || true
    fi
    rm -f "$WEB_UNIT_DST"
    systemctl --user daemon-reload 2>/dev/null || true
    rm -rf "$WEB_DIR"

    if sudo systemctl list-unit-files octollama-daemon.service >/dev/null 2>&1; then
        sudo systemctl disable --now octollama-daemon.service 2>/dev/null || true
    fi
    sudo rm -f "$DAEMON_UNIT_DST"
    sudo systemctl daemon-reload
    sudo rm -rf "$DAEMON_DIR"

    read -r -p "Also remove the state directory ($STATE_DIR) and NFS exports for remote hosts? [y/N] " ANSWER || true
    case "$ANSWER" in
        [yY]*)
            sudo rm -rf "$STATE_DIR" "$HOSTS_BASE"
            sudo rm -f "$EXPORTS_FILE"
            sudo exportfs -ra 2>/dev/null || true
            ;;
    esac

    echo
    echo "OctoLlama has been removed."
    echo "Ollama, LiteLLM, Open WebUI, and nfs-kernel-server are left in place by default -"
    echo "other tools/data on this machine may depend on them."

    read -r -p "Remove LiteLLM too (uv tool + its config)? [y/N] " ANSWER || true
    case "$ANSWER" in
        [yY]*)
            command -v uv >/dev/null 2>&1 && uv tool uninstall litellm || true
            rm -rf "$HOME/.config/octollama"
            ;;
    esac

    read -r -p "Remove Open WebUI too (uv tool + its systemd --user unit)? [y/N] " ANSWER || true
    case "$ANSWER" in
        [yY]*)
            systemctl --user disable --now open-webui.service 2>/dev/null || true
            rm -f "$HOME/.config/systemd/user/open-webui.service"
            systemctl --user daemon-reload 2>/dev/null || true
            command -v uv >/dev/null 2>&1 && uv tool uninstall open-webui || true
            ;;
    esac

    read -r -p "Remove Ollama too? WARNING: this deletes ALL downloaded models. [y/N] " ANSWER || true
    case "$ANSWER" in
        [yY]*)
            sudo systemctl disable --now ollama.service 2>/dev/null || true
            sudo rm -f /etc/systemd/system/ollama.service
            sudo systemctl daemon-reload
            sudo rm -f "$(command -v ollama)" 2>/dev/null || true
            sudo rm -rf /usr/share/ollama
            ;;
    esac

    read -r -p "Remove nfs-kernel-server too (stops NFS entirely on this host)? [y/N] " ANSWER || true
    case "$ANSWER" in
        [yY]*) sudo apt-get remove -y nfs-kernel-server ;;
    esac

    echo "Done."
}

if [ "${1:-}" = "--uninstall" ]; then
    remove_app
    exit 0
fi

# =============================================================================
#  Detect an existing install
# =============================================================================
if [ -f "$INSTALLED_VERSION_FILE" ]; then
    INSTALLED_VERSION="$(cat "$INSTALLED_VERSION_FILE")"
    case "$(_compare_versions "$INSTALLED_VERSION" "$NEW_VERSION")" in
        older)
            echo "Installed version: $INSTALLED_VERSION. Update available: $NEW_VERSION."
            read -r -p "Update now? [Y/n] " ANSWER || true
            case "$ANSWER" in
                [nN]*) echo "Cancelled." ; exit 0 ;;
            esac
            ;;
        same)
            echo "Version $NEW_VERSION is already installed."
            read -r -p "Reinstall it anyway? [y/N] " ANSWER || true
            case "$ANSWER" in
                [yY]*) ;;
                *) echo "Cancelled." ; exit 0 ;;
            esac
            ;;
        newer)
            echo "WARNING: the installed version ($INSTALLED_VERSION) is newer than the one in this checkout ($NEW_VERSION)."
            read -r -p "Overwrite the newer version with the older one? [y/N] " ANSWER || true
            case "$ANSWER" in
                [yY]*) ;;
                *) echo "Cancelled." ; exit 0 ;;
            esac
            ;;
    esac
fi

echo "Installing OctoLlama $NEW_VERSION..."
echo

echo "=== [1/6] Ollama ==="
if command -v ollama >/dev/null 2>&1; then
    echo "Already installed - skipping."
else
    echo "Installing (official installer from ollama.com, may ask for your sudo password)..."
    curl -fsSL https://ollama.com/install.sh | sh
fi

echo
echo "=== [2/6] LiteLLM ==="
_uv_binary() {
    command -v uv 2>/dev/null && return 0
    [ -x "$HOME/.local/bin/uv" ] && { echo "$HOME/.local/bin/uv"; return 0; }
    return 1
}
if UV="$(_uv_binary)"; then
    :
else
    echo "Installing uv (manages Python tools without touching the system pip)..."
    curl -LsSf https://astral.sh/uv/install.sh | sh
    UV="$(_uv_binary)"
fi
if command -v litellm >/dev/null 2>&1 || [ -x "$HOME/.local/bin/litellm" ]; then
    echo "Already installed - skipping."
else
    echo "Installing LiteLLM..."
    "$UV" tool install 'litellm[proxy]'
fi

echo
echo "=== [3/6] Open WebUI ==="
if command -v open-webui >/dev/null 2>&1 || [ -x "$HOME/.local/bin/open-webui" ]; then
    echo "Already installed - skipping."
else
    # WHY: Open WebUI (as of 2026) doesn't support the newest system Python yet -
    # uv pulls in a compatible Python 3.11 itself, no apt/root needed
    # (same pattern as Ollama Manager, see web/openwebui_manager.py).
    echo "Installing Open WebUI (Python 3.11 via uv, this may take a while)..."
    "$UV" tool install --python 3.11 open-webui
fi

echo
echo "=== [4/6] NFS server (exports for remote hosts) ==="
if command -v exportfs >/dev/null 2>&1; then
    echo "nfs-kernel-server already installed - skipping."
else
    sudo apt-get install -y nfs-kernel-server
fi
sudo mkdir -p "$HOSTS_BASE" /etc/exports.d
sudo systemctl enable --now nfs-kernel-server

echo
echo "=== [5/6] octollama-daemon (root, systemd system unit) ==="
sudo mkdir -p "$DAEMON_DIR"
sudo cp "$DAEMON_SRC/octollama_daemon.py" "$DAEMON_SRC/requirements.txt" "$DAEMON_DIR/"
sudo cp "$SCRIPT_DIR/VERSION" "$DAEMON_DIR/VERSION"
[ -d "$DAEMON_DIR/.venv" ] || sudo python3 -m venv "$DAEMON_DIR/.venv"
sudo "$DAEMON_DIR/.venv/bin/pip" install -q -r "$DAEMON_DIR/requirements.txt"
sudo mkdir -p "$STATE_DIR"
# WHY: the daemon (root) can write anywhere anyway, but the web panel (regular
# user) also needs write access to state.json/status.json in this directory.
sudo chown "$(id -u):$(id -g)" "$STATE_DIR"
sudo cp "$DAEMON_SRC/systemd/octollama-daemon.service" "$DAEMON_UNIT_DST"
sudo systemctl daemon-reload
sudo systemctl enable octollama-daemon.service
sudo systemctl restart octollama-daemon.service

echo
echo "=== [6/6] octollama-web (no root, systemd --user) ==="
mkdir -p "$WEB_DIR/templates" "$WEB_DIR/static" "$WEB_DIR/lang"
cp "$WEB_SRC"/*.py "$WEB_SRC/requirements.txt" "$WEB_DIR/"
cp "$SCRIPT_DIR/VERSION" "$INSTALLED_VERSION_FILE"
cp -r "$WEB_SRC/templates/." "$WEB_DIR/templates/"
cp -r "$WEB_SRC/static/." "$WEB_DIR/static/"
cp -r "$WEB_SRC/lang/." "$WEB_DIR/lang/"
# WHY: hosts.json is user config (the list of Ollama hosts) - don't overwrite
# it on a re-run of the installer if the user has already customized it.
[ -f "$WEB_DIR/hosts.json" ] || cp "$WEB_SRC/hosts.json" "$WEB_DIR/"
[ -d "$WEB_DIR/.venv" ] || python3 -m venv "$WEB_DIR/.venv"
"$WEB_DIR/.venv/bin/pip" install -q -r "$WEB_DIR/requirements.txt"

# WHY: only ask on a fresh install - re-running the installer to update
# must NOT silently reset a previously chosen port back to 5000.
if [ -f "$PORT_FILE" ]; then
    WEB_PORT="$(cat "$PORT_FILE")"
else
    read -r -p "Port for the web panel [5000]: " PORT_INPUT || true
    WEB_PORT="${PORT_INPUT:-5000}"
    case "$WEB_PORT" in
        ''|*[!0-9]*|0)
            echo "Not a valid port number - using 5000." >&2
            WEB_PORT=5000
            ;;
    esac
    echo "$WEB_PORT" > "$PORT_FILE"
fi

mkdir -p "$(dirname "$WEB_UNIT_DST")"
sed "s/{{PORT}}/$WEB_PORT/" "$WEB_SRC/systemd/octollama-web.service" > "$WEB_UNIT_DST"
systemctl --user daemon-reload
systemctl --user enable octollama-web.service
systemctl --user restart octollama-web.service

echo
echo "Done. OctoLlama $NEW_VERSION installed."
if [ ! -f "$WEB_DIR/credentials.json" ]; then
    echo "Set your panel login credentials (asked once, password entered twice to confirm):"
    (cd "$WEB_DIR" && ./.venv/bin/python3 manage_users.py)
fi
echo "Web panel: http://$(hostname -I 2>/dev/null | awk '{print $1}'):$WEB_PORT"
echo "To uninstall: ./install.sh --uninstall"
