#!/bin/bash
# =============================================================================
#  Installer for the MANAGEMENT HOST (the one that will run the web panel).
#
#  Installs/updates EVERYTHING this host needs, in one go:
#    1) Ollama (official installer from ollama.com)
#    2) LiteLLM (gateway aggregator, via `uv tool install`, no root)
#    3) Open WebUI (chat panel, `uv tool install --python 3.11`, no root) -
#       installs the binary only, does NOT start/enable the service - that's
#       left to the Start/autostart button in the panel's WebUI tab on purpose
#       (heavy service, not everyone wants it running right away)
#    4) nfs-kernel-server - export server for remote hosts (BC-250 etc.),
#       per-host exports themselves are managed by the daemon (Slave tab)
#    5) ollama-manager-daemon (root, system systemd unit) - controls the local
#       Ollama service EXCLUSIVELY through state.json (see README.md, Architecture)
#    6) ollama-manager-web (no root, systemd --user) - the login web panel
#
#  For a REMOTE host (e.g. BC-250) that only needs Ollama + the daemon, not the
#  web panel or LiteLLM - use the script generated by the web panel itself
#  (README.md, "Multi-host" section), not this file.
#
#  Run:  ./install.sh
# =============================================================================
set -euo pipefail

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"
DAEMON_SRC="$SCRIPT_DIR/daemon"
WEB_SRC="$SCRIPT_DIR/web"

DAEMON_DIR="/opt/ollama-manager/daemon"
STATE_DIR="/var/lib/ollama-manager/state"
DAEMON_UNIT_DST="/etc/systemd/system/ollama-manager-daemon.service"

WEB_DIR="$HOME/.local/share/ollama-manager-web"
WEB_UNIT_DST="$HOME/.config/systemd/user/ollama-manager-web.service"

echo "=== [1/6] Ollama ==="
if command -v ollama >/dev/null 2>&1; then
    echo "Already installed - skipping."
else
    echo "Installing (official installer from ollama.com, may ask for your sudo password)..."
    curl -fsSL https://ollama.com/install.sh | sh
fi

echo
echo "=== [2/6] LiteLLM ==="
_uv_binary() {
    command -v uv 2>/dev/null && return 0
    [ -x "$HOME/.local/bin/uv" ] && { echo "$HOME/.local/bin/uv"; return 0; }
    return 1
}
if UV="$(_uv_binary)"; then
    :
else
    echo "Installing uv (manages Python tools without touching the system pip)..."
    curl -LsSf https://astral.sh/uv/install.sh | sh
    UV="$(_uv_binary)"
fi
if command -v litellm >/dev/null 2>&1 || [ -x "$HOME/.local/bin/litellm" ]; then
    echo "Already installed - skipping."
else
    echo "Installing LiteLLM..."
    "$UV" tool install 'litellm[proxy]'
fi

echo
echo "=== [3/6] Open WebUI ==="
if command -v open-webui >/dev/null 2>&1 || [ -x "$HOME/.local/bin/open-webui" ]; then
    echo "Already installed - skipping."
else
    # WHY: Open WebUI (as of 2026) doesn't support the newest system Python yet -
    # uv pulls in a compatible Python 3.11 itself, no apt/root needed
    # (same pattern as Ollama Manager, see web/openwebui_manager.py).
    echo "Installing Open WebUI (Python 3.11 via uv, this may take a while)..."
    "$UV" tool install --python 3.11 open-webui
fi

echo
echo "=== [4/6] NFS server (exports for remote hosts) ==="
if command -v exportfs >/dev/null 2>&1; then
    echo "nfs-kernel-server already installed - skipping."
else
    sudo apt-get install -y nfs-kernel-server
fi
sudo mkdir -p /srv/ollama-manager/hosts /etc/exports.d
sudo systemctl enable --now nfs-kernel-server

echo
echo "=== [5/6] ollama-manager-daemon (root, systemd system unit) ==="
sudo mkdir -p "$DAEMON_DIR"
sudo cp "$DAEMON_SRC/ollama_manager_daemon.py" "$DAEMON_SRC/requirements.txt" "$DAEMON_DIR/"
[ -d "$DAEMON_DIR/.venv" ] || sudo python3 -m venv "$DAEMON_DIR/.venv"
sudo "$DAEMON_DIR/.venv/bin/pip" install -q -r "$DAEMON_DIR/requirements.txt"
sudo mkdir -p "$STATE_DIR"
# WHY: the daemon (root) can write anywhere anyway, but the web panel (regular
# user) also needs write access to state.json/status.json in this directory.
sudo chown "$(id -u):$(id -g)" "$STATE_DIR"
sudo cp "$DAEMON_SRC/systemd/ollama-manager-daemon.service" "$DAEMON_UNIT_DST"
sudo systemctl daemon-reload
sudo systemctl enable ollama-manager-daemon.service
sudo systemctl restart ollama-manager-daemon.service

echo
echo "=== [6/6] ollama-manager-web (no root, systemd --user) ==="
mkdir -p "$WEB_DIR/templates" "$WEB_DIR/static" "$WEB_DIR/lang"
cp "$WEB_SRC"/*.py "$WEB_SRC/requirements.txt" "$WEB_DIR/"
cp -r "$WEB_SRC/templates/." "$WEB_DIR/templates/"
cp -r "$WEB_SRC/static/." "$WEB_DIR/static/"
cp -r "$WEB_SRC/lang/." "$WEB_DIR/lang/"
# WHY: hosts.json is user config (the list of Ollama hosts) - don't overwrite
# it on a re-run of the installer if the user has already customized it.
[ -f "$WEB_DIR/hosts.json" ] || cp "$WEB_SRC/hosts.json" "$WEB_DIR/"
[ -d "$WEB_DIR/.venv" ] || python3 -m venv "$WEB_DIR/.venv"
"$WEB_DIR/.venv/bin/pip" install -q -r "$WEB_DIR/requirements.txt"
mkdir -p "$(dirname "$WEB_UNIT_DST")"
cp "$WEB_SRC/systemd/ollama-manager-web.service" "$WEB_UNIT_DST"
systemctl --user daemon-reload
systemctl --user enable ollama-manager-web.service
systemctl --user restart ollama-manager-web.service

echo
echo "Done."
if [ ! -f "$WEB_DIR/credentials.json" ]; then
    echo "Before logging into the panel, set your login credentials:"
    echo "  cd \"$WEB_DIR\" && ./.venv/bin/python3 manage_users.py"
fi
echo "Web panel: http://$(hostname -I 2>/dev/null | awk '{print $1}'):5000"
